# Generated by Django 5.1.7 on 2025-05-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="unnamed.jpg", null=True, upload_to="media/"
            ),
        ),
    ]
